### ISSUE TITLE
Multiple keywords support?

### ISSUE THREAD

**Issue by Yasand123** [Blacksuan19/plasma-wallpaper-wallhaven-reborn#3]
This is such an awesome piece of software. It works really nicely with nice QoL features. However I couldn't help but notice that there's no way to enter multiple keywords as there's only one field. The way multiple keywords would work is to randomly pick 1 entry from the list and use that as the search query to pull new wallpapers.

So for example. I want "gaming", and I want "nature", and "space". Currently, I can only pick one. But it would be nice if I can add all of these keywords in a list and the software would pick one randomly when refreshing the wallpaper.

**Comment by Blacksuan19** [comment]
You can already do multiple keywords in the same text field, just separate them by a space

**Comment by Blacksuan19** [comment]
That's a good idea, I'll see what I can do

**Comment by Blacksuan19** [comment]
I realized the current API behavior is actually weird and quite unusual, even I thought it would choose one of the several tags given rather than search for something that has all tags, I will make this the default behavior since it makes more sense, I doubt many people search for images with multiple tags, that's just way too specific.
