### ISSUE TITLE
Remove random

### ISSUE THREAD

**Issue by chrisemke** [Blacksuan19/plasma-wallpaper-wallhaven-reborn#8]
Hello, a while ago I've open this PR: https://github.com/subpop/wallhaven-wallpaper-plasma/pull/3

at that time I discover the page 0 on random is already randomized so we don't need to make a "virtual random".

This causes an issue with query's that don't have a lot of pages aswell, sometimes it get an image and sometimes it get a black screen

Do you think it makes sense to make this change?

**Comment by Blacksuan19** [comment]
I understand what you mean, the API returns randomized results for each call unless the same seed is passed so it's always fine to just pick the first image in the results essentially, in your pull request I see you are removing the checks for random sorting and always sending page attribute, that seems redundant considering random is always random and might lead to the issue you described when there are 24 or less results thus only 1 page, for the same reason, setting page and index when on random sorting is redundant as well, the only part that makes sense in your pull request is not setting index in the else block and just using `main.currentIndex`

**Comment by Blacksuan19** [comment]
this prompted me to recheck the selection logic in that code, I found a glaring issue where the index doesn't wrap and will lead to failure when overflow even though there are wallpapers available, I believe that is the issue you ran into with queries that don't have many results (tested with `@lumberjacck goth`), that is now fixed, I don't see any harm in leaving the current re-randomization of index in the else block on random sorting because it is parameterized by the size of the output so the above issue will never occur.
