### ISSUE TITLE
Cache latest downloaded wallpaper.

### ISSUE THREAD

**Issue by prykhodev** [Blacksuan19/plasma-wallpaper-wallhaven-reborn#9]
Right now when i'm logging into my machine there is always error with loading new wallpaper because of connection trough wi-fi being established. It would be nice if there will be some wallpaper instead of black screen. So i thing the solution is to cache only one image that  was downloaded last and display it in such cases.

**Comment by Blacksuan19** [comment]
the previously used wallpaper remains if you just logout or if the device sleeps, the only case where there is no wallpaper is if you reboot, I assume you mean after a reboot?

I don't want to implement caching on purpose, mainly because the whole point of using this plugin is to get random wallpapers for me and I rarely reboot my laptop, I implemented the retry request feature to address the issue of black screen at the start until you manually refresh after connecting to a network, from what you are saying this seems to work fine, I don't think 5-10 seconds of black screen justifies implementing caching. nonetheless, you can manually replace the blackscreen.jpg image in the plugin directory with whatever image you want, maybe I will expose that on the config page so you can set a default wallpaper when none can be fetched.

**Comment by samxl001** [comment]
Could you add a delay when the plugin starts when the system is started? I have the same problem. When I boot up my laptop it takes a while to establish a wifi connection and the screen remain black until I refresh the wallpaper manually. I think the retry request is not working. So maybe adding 20 seconds delay to the plugin start up will solve the problem so the system has enough time to establish connection.
I always turn off my laptop after use so getting black screen on each boot is not ideal

**Comment by Blacksuan19** [comment]
I'm not adding an intentional delay, seems very unnecessary. The retry feature works as intended, you'll get notifications when it happens, make sure you're using the latest version, it retries 3 times every 5 seconds so your wi-fi has 10-15 seconds to connect which is enough time to connect normally, Maybe I will expose the delay timer so you can set it to whatever amount of time your wifi takes to connect.

**Comment by samxl001** [comment]
I downloaded from KDE store as you described in the main page. So I should have the latest version. But I am not getting any notifications when it fails to download a wallpaper. How can I check what version I am using now?

**Comment by Blacksuan19** [comment]
don't install from distro repos, install directly from get new plugins in wallpaper settings, you will get a window with all files, select the one with the latest version (usually the biggest number in file name)

[Screencast_20241107_005353.webm](https://github.com/user-attachments/assets/9826c73f-d33b-4a88-802a-c447d346693e)

**Comment by Blacksuan19** [comment]
I have added a commit that exposes the number of retries and the delay between each retry in the configuration page, that should allow you to configure the retry according to how long it takes to connect.
